name: Build App

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/**'
      - 'Configs/**'
      - 'PCL.Mac/**'
      - 'PCL.Mac.Core/**'
      - 'PCL.Mac.xcodeproj/**'
      - 'Resources/**'

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Set version
        run: echo "BUILD_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_ENV
      
      - name: Generate Secrets.properties
        run: |
          cat <<EOF > ./Resources/Secrets.properties
          CURSE_FORGE_API_KEY=${{ secrets.CURSE_FORGE_API_KEY }}
          EOF

      - name: Build app
        run: |
          echo "Build number: $BUILD_NUMBER"
          xcodebuild archive \
            -project PCL.Mac.xcodeproj -scheme PCL.Mac -configuration Debug \
            CURRENT_PROJECT_VERSION=$BUILD_NUMBER \
            -archivePath build

      - name: Prepare app artifact directory
        run: |
          mkdir "PCL.Mac-artifact"
          cp -r ./build.xcarchive/Products/Applications/PCL.Mac.app ./PCL.Mac-artifact/PCL.Mac.app
          cp -r ./build.xcarchive ./PCL.Mac-artifact/build.xcarchive

      - name: Upload app artifact
        uses: actions/upload-artifact@v7
        with:
          name: PCL.Mac.Refactor-${{ env.BUILD_NUMBER }}
          path: ./PCL.Mac-artifact