name: PR Test

on:
  pull_request:
    paths:
      - "Configs/**"
      - ".github/workflows/**"
      - "PCL.Mac/**"
      - "PCL.Mac.Core/**"
      - "PCL.Mac.xcodeproj/**"
      - "Resources/**"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      build_configuration: Debug
      upload_artifact: false
    secrets: inherit