name: Build and release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      build_configuration: Release
      upload_artifact: true
    secrets: inherit
  
  release:
    runs-on: macos-26
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Get version
        run: |
          echo "BUILD_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_ENV
          VERSION_NUMBER=$(grep '^MARKETING_VERSION' Configs/Base.xcconfig | cut -d '=' -f2 | xargs)
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_ENV
          echo "TAG_NAME=v$VERSION_NUMBER" >> $GITHUB_ENV
      
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: PCL.Mac-artifact.zip
          path: ./artifact
      
      - name: Process artifact
        run: |
          ls -l
          find ./artifact
          ditto -x -k ./artifact/PCL.Mac-artifact.zip ./artifact
          ditto -c -k --keepParent ./artifact/PCL.Mac.app "./PCL.Mac-${{ env.TAG_NAME }}.zip"
          ditto -c -k --keepParent ./artifact/build.xcarchive ./build.xcarchive.zip
      
      - name: Create release
        run: |
          gh release create $TAG_NAME \
            "PCL.Mac-${{ env.TAG_NAME }}.zip" \
            "build.xcarchive.zip" \
            --title $VERSION_NUMBER \
            --generate-notes \
            --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
